@startuml

Client --> DataAccessObject : "uses"
DataAccessObject ..> Data : "creates"
Client ..>  Data : "creates/uses"
DataAccessObject --> DataSource : "accesses"
DataAccessObject --> ResultSet : "uses"
DataSource ..> ResultSet : "creates"

DataAccessObject : void create
DataAccessObject : Object read
DataAccessObject : void update
DataAccessObject : void delete

class Data << TransferObject >>

@enduml