@startuml
frame "Layer 3" {
  [Component 3.1] -> [Component 3.2]
}
frame "Layer 2" {
  [Component 2.1]
  [Component 2.2]
  [Component 2.3]
}
frame "Layer 1" {
  [Component 1.1]
  [Component 1.2]
  [Nuevo componente]
}
[Component 3.1]-->[Component 2.1]
[Component 3.2]-->[Component 2.2]
[Component 3.2]-->[Component 2.3]
[Component 2.1]-->[Component 1.1]
[Component 2.2]-->[Component 1.2]
[Component 2.3]-->[Component 1.1]
@enduml

